### ISSUE TITLE
Fix wearables compilation 

### ISSUE THREAD

**Issue by lrapetti** [robotology/wearables#132]
**Describe the bug**
Compilation is failing after https://github.com/robotology/wearables/pull/131 (e.g. see CI failure) with the following error
```
[ 64%] Building CXX object devices/IWearRemapper/CMakeFiles/IWearRemapper.dir/src/IWearRemapper.cpp.o
/Users/lorenzorapetti/Software/robotology-superbuild/src/wearables/devices/IWearRemapper/src/IWearRemapper.cpp:13:10: fatal error: 'thrift/WearableMetadataService.h' file not found
#include "thrift/WearableMetadataService.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
The problem was not spotted earlier because:
- I didn't test compilation on a clean build
- Github actions were disabled because of >60 days inactivity on the repo (see https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow)
